In [8]:
import numpy as np
from catboost import CatBoostClassifier, Pool
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectKBest, chi2

from pandas import DataFrame
from sklearn.pipeline import Pipeline
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.feature_selection import RFECV
from sklearn.multioutput import MultiOutputClassifier
from sklearn.multiclass import OneVsRestClassifier

In [9]:
X, y = make_classification(n_samples=3000, n_clusters_per_class=10, n_classes=5, n_informative=500, n_features=800)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [10]:
X, y

(array([[ 1.81055010e+01, -1.61599167e+00,  7.30975118e+00, ...,
          1.42385579e+01, -7.02584883e-03, -1.53902283e+00],
        [ 1.09413744e+01,  1.93858491e+01, -3.62767618e+00, ...,
         -8.28253386e+00, -1.23118667e+00,  1.78319433e+00],
        [ 8.37850343e-03, -1.39596252e+00,  7.67774518e+00, ...,
         -4.88235195e+00, -4.31813739e-01, -1.05789620e+00],
        ...,
        [-6.55160280e+00,  9.17003769e+00,  1.73408793e+01, ...,
          1.06377939e+01,  8.69198566e-01, -5.52076350e-01],
        [ 4.71652692e+00, -6.85240956e+00, -1.51056482e-01, ...,
         -3.02939526e+01,  1.86156661e-01,  6.77119240e-01],
        [ 9.90165456e+00,  4.60382495e+00,  2.39801363e+01, ...,
         -1.04542674e+01, -4.29090610e-01,  8.57762933e-01]]),
 array([1, 1, 3, ..., 1, 4, 1]))

In [28]:
# Define multi output classifier pipeline with feature selection
estimator = CatBoostClassifier(allow_writing_files=False, n_estimators=500,
                                       verbose=2, task_type="CPU",
                                       early_stopping_rounds=10)
mo_clf = MultiOutputClassifier(estimator, n_jobs=-1)

mo_clf.fit(X=X2, Y=y2)

ValueError: y must have at least two dimensions for multi-output regression but has only one.

In [26]:
mo_clf.predict_proba(X[:2])

[array([[0.62980304, 0.37019696],
        [0.42893726, 0.57106274]]),
 array([[0.32968046, 0.67031954],
        [0.81365713, 0.18634287]]),
 array([[0.82188407, 0.17811593],
        [0.74144545, 0.25855455]]),
 array([[0.49556256, 0.50443744],
        [0.80247267, 0.19752733]]),
 array([[0.85678383, 0.14321617],
        [0.86630391, 0.13369609]]),
 array([[0.90770207, 0.09229793],
        [0.88434945, 0.11565055]]),
 array([[0.66510693, 0.33489307],
        [0.4574056 , 0.5425944 ]]),
 array([[0.72068589, 0.27931411],
        [0.3900518 , 0.6099482 ]])]

In [27]:
mo_clf.classes_

[array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1]),
 array([0, 1])]

In [8]:
X2, y2 = make_multilabel_classification(n_labels=5, random_state=0, n_features=2000, n_samples=5000)

In [9]:
y2 = np.random.choice(['yes', 'no', 'maybe'], size=5000)

In [29]:
for i in y2:
    if i.sum() > 3:
        print('yes')
    else:
        print('no')

yes
yes
no
no
yes
no
no
yes
yes
yes
yes
no
yes
yes
yes
no
no
no
no
no
no
yes
no
no
yes
yes
no
no
yes
yes
yes
yes
no
yes
yes
yes
yes
yes
yes
yes
no
yes
no
yes
no
yes
yes
no
yes
no
no
yes
no
yes
no
yes
yes
no
no
yes
no
yes
no
yes
yes
yes
yes
no
yes
no
no
no
no
yes
yes
yes
yes
no
no
no
yes
yes
yes
no
no
yes
yes
no
no
yes
no
no
no
no
yes
yes
no
yes
yes
yes
yes
yes
no
yes
yes
no
yes
no
no
yes
yes
yes
yes
no
no
no
yes
yes
yes
yes
yes
no
no
yes
yes
yes
no
yes
yes
yes
yes
no
yes
no
yes
yes
no
yes
no
yes
no
yes
no
no
yes
yes
yes
yes
yes
no
yes
yes
yes
no
yes
yes
yes
yes
yes
no
no
yes
yes
yes
yes
yes
yes
no
no
no
no
yes
yes
no
yes
yes
yes
yes
yes
no
yes
no
no
no
no
yes
yes
yes
yes
no
yes
yes
no
yes
no
yes
yes
no
yes
no
no
no
yes
no
no
yes
yes
yes
no
yes
yes
no
yes
yes
no
yes
yes
no
yes
yes
no
no
yes
yes
no
yes
yes
no
yes
yes
yes
yes
yes
no
no
yes
yes
yes
yes
no
no
no
no
yes
no
no
yes
no
no
no
no
no
yes
yes
yes
no
no
yes
yes
no
yes
no
yes
no
no
no
yes
no
yes
yes
no
yes
no
yes
no
yes
yes
yes
yes
y

In [10]:
train = Pool(data=X2, label=y2)

In [11]:
cb_estimator = CatBoostClassifier(allow_writing_files=False, n_estimators=200,
                                       verbose=2, task_type="CPU",
                                       early_stopping_rounds=10, loss_function='MultiClass')
cb_estimator.fit(X=train)

Learning rate set to 0.334657
0:	learn: 1.0965656	total: 129ms	remaining: 25.6s
2:	learn: 1.0931905	total: 210ms	remaining: 13.8s
4:	learn: 1.0892748	total: 302ms	remaining: 11.8s
6:	learn: 1.0861657	total: 402ms	remaining: 11.1s
8:	learn: 1.0833607	total: 646ms	remaining: 13.7s
10:	learn: 1.0798325	total: 765ms	remaining: 13.1s
12:	learn: 1.0774444	total: 926ms	remaining: 13.3s
14:	learn: 1.0745706	total: 1.05s	remaining: 13s
16:	learn: 1.0719325	total: 1.17s	remaining: 12.6s
18:	learn: 1.0686605	total: 1.33s	remaining: 12.7s
20:	learn: 1.0655764	total: 1.47s	remaining: 12.5s
22:	learn: 1.0619078	total: 1.66s	remaining: 12.8s
24:	learn: 1.0589081	total: 1.79s	remaining: 12.5s
26:	learn: 1.0554928	total: 1.98s	remaining: 12.7s
28:	learn: 1.0506202	total: 2.16s	remaining: 12.7s
30:	learn: 1.0452232	total: 2.32s	remaining: 12.7s
32:	learn: 1.0408881	total: 2.47s	remaining: 12.5s
34:	learn: 1.0362366	total: 2.62s	remaining: 12.4s
36:	learn: 1.0318060	total: 2.77s	remaining: 12.2s
38:	lear

In [12]:
cb_estimator.predict_proba(X[:2])

array([[0.34684382, 0.27928849, 0.37386769],
       [0.32090996, 0.38713343, 0.2919566 ]])

In [31]:
X2, y2

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array(['no', 'yes', 'no', ..., 'yes', 'maybe', 'maybe'], dtype='<U5'))

In [38]:
est = CatBoostClassifier(allow_writing_files=False, n_estimators=200,
                                       verbose=2, task_type="CPU",
                                       early_stopping_rounds=10, loss_function='Logloss')

In [39]:
model = OneVsRestClassifier(est)

In [40]:
model.fit(X2, y2)

Learning rate set to 0.089609
0:	learn: 0.6831597	total: 96.7ms	remaining: 19.2s
2:	learn: 0.6678013	total: 173ms	remaining: 11.3s
4:	learn: 0.6574186	total: 256ms	remaining: 9.97s
6:	learn: 0.6503031	total: 340ms	remaining: 9.37s
8:	learn: 0.6451325	total: 411ms	remaining: 8.72s
10:	learn: 0.6413096	total: 486ms	remaining: 8.34s
12:	learn: 0.6381958	total: 558ms	remaining: 8.02s
14:	learn: 0.6355353	total: 618ms	remaining: 7.62s
16:	learn: 0.6336758	total: 708ms	remaining: 7.62s
18:	learn: 0.6320063	total: 773ms	remaining: 7.36s
20:	learn: 0.6304405	total: 833ms	remaining: 7.1s
22:	learn: 0.6289397	total: 883ms	remaining: 6.79s
24:	learn: 0.6278875	total: 947ms	remaining: 6.63s
26:	learn: 0.6263278	total: 1.01s	remaining: 6.46s
28:	learn: 0.6248368	total: 1.05s	remaining: 6.21s
30:	learn: 0.6234955	total: 1.13s	remaining: 6.16s
32:	learn: 0.6222328	total: 1.21s	remaining: 6.12s
34:	learn: 0.6209821	total: 1.29s	remaining: 6.11s
36:	learn: 0.6198813	total: 1.36s	remaining: 5.99s
38:	le

124:	learn: 0.5484400	total: 4.29s	remaining: 2.57s
126:	learn: 0.5464158	total: 4.34s	remaining: 2.49s
128:	learn: 0.5443652	total: 4.42s	remaining: 2.43s
130:	learn: 0.5425890	total: 4.48s	remaining: 2.36s
132:	learn: 0.5404444	total: 4.54s	remaining: 2.29s
134:	learn: 0.5386317	total: 4.62s	remaining: 2.22s
136:	learn: 0.5366272	total: 4.67s	remaining: 2.15s
138:	learn: 0.5348486	total: 4.72s	remaining: 2.07s
140:	learn: 0.5326534	total: 4.78s	remaining: 2s
142:	learn: 0.5310416	total: 4.84s	remaining: 1.93s
144:	learn: 0.5291273	total: 4.93s	remaining: 1.87s
146:	learn: 0.5272842	total: 4.99s	remaining: 1.8s
148:	learn: 0.5254349	total: 5.04s	remaining: 1.73s
150:	learn: 0.5233163	total: 5.1s	remaining: 1.66s
152:	learn: 0.5211808	total: 5.17s	remaining: 1.59s
154:	learn: 0.5192904	total: 5.22s	remaining: 1.52s
156:	learn: 0.5179639	total: 5.27s	remaining: 1.44s
158:	learn: 0.5162988	total: 5.33s	remaining: 1.38s
160:	learn: 0.5144691	total: 5.39s	remaining: 1.31s
162:	learn: 0.513

OneVsRestClassifier(estimator=<catboost.core.CatBoostClassifier object at 0x29f69f400>)

In [42]:
model.predict_proba(X2[:5])

array([[0.40139725, 0.38505204, 0.21355071],
       [0.23489329, 0.25877528, 0.50633143],
       [0.32104005, 0.40766178, 0.27129817],
       [0.43807989, 0.27467434, 0.28724577],
       [0.2690471 , 0.46941242, 0.26154048]])

In [50]:
z = model.estimators_[0]

In [51]:
z.best_score_

{'learn': {'Logloss': 0.49623490562976874}}

In [61]:
z.feature_importances_

array([0., 0., 0., ..., 0., 0., 0.])

In [62]:
z.feature_names_

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 '50',
 '51',
 '52',
 '53',
 '54',
 '55',
 '56',
 '57',
 '58',
 '59',
 '60',
 '61',
 '62',
 '63',
 '64',
 '65',
 '66',
 '67',
 '68',
 '69',
 '70',
 '71',
 '72',
 '73',
 '74',
 '75',
 '76',
 '77',
 '78',
 '79',
 '80',
 '81',
 '82',
 '83',
 '84',
 '85',
 '86',
 '87',
 '88',
 '89',
 '90',
 '91',
 '92',
 '93',
 '94',
 '95',
 '96',
 '97',
 '98',
 '99',
 '100',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '120',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126',
 '127',
 '128',
 '129',
 '130',
 '131',
 '132',
 '133',
 '134',
 '135',
 '136',
 '137',
 '138'

In [65]:
z.get_best_score()

{'learn': {'Logloss': 0.49623490562976874}}

In [82]:
z.feature_importances_.argsort(order='descending')

ValueError: Cannot specify order when the array has no fields.

In [69]:
model.classes_

array(['maybe', 'no', 'yes'], dtype='<U5')

In [90]:
z.select_features(X=X2[:-100], y=y2[:-100], eval_set=(X2[-100:], y2[-100:]))

CatBoostError: Model was already fitted. Set train_final_model to False or use not fitted model.

In [89]:
y2[-100:].shape

(100,)