In [44]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np
import pandas as pd

In [34]:
s = MinMaxScaler(feature_range=(1,10), )

In [35]:
X = np.random.random(size=(10,1000))
X

array([[0.82973234, 0.53472896, 0.08274621, ..., 0.5443761 , 0.38365422,
        0.85267641],
       [0.43208179, 0.90891525, 0.37526489, ..., 0.5370653 , 0.876483  ,
        0.11977878],
       [0.06139854, 0.03786435, 0.65827961, ..., 0.167192  , 0.76608837,
        0.52466285],
       ...,
       [0.16787458, 0.14264522, 0.82775534, ..., 0.8394617 , 0.53160039,
        0.81147545],
       [0.40549961, 0.41427257, 0.79031209, ..., 0.93441814, 0.61461481,
        0.11183651],
       [0.53047373, 0.05432578, 0.85170591, ..., 0.14206299, 0.87954903,
        0.91280657]])

In [36]:
w = np.random.random(size=(1000, 1)) + 1
w

array([[1.06164489],
       [1.11721332],
       [1.47080824],
       [1.13082349],
       [1.39932543],
       [1.86508609],
       [1.89754949],
       [1.66619147],
       [1.31103179],
       [1.02774858],
       [1.57684837],
       [1.49533635],
       [1.95953381],
       [1.45702692],
       [1.13766195],
       [1.96876924],
       [1.43305563],
       [1.20229958],
       [1.92425925],
       [1.82225999],
       [1.29986732],
       [1.20484978],
       [1.26387173],
       [1.09936822],
       [1.52488745],
       [1.62976567],
       [1.72594481],
       [1.39123506],
       [1.39147599],
       [1.18722409],
       [1.17289634],
       [1.71808351],
       [1.07334567],
       [1.23946335],
       [1.83262827],
       [1.12920674],
       [1.37067859],
       [1.34629974],
       [1.9604981 ],
       [1.19187844],
       [1.59838161],
       [1.73130811],
       [1.81492855],
       [1.87209757],
       [1.05987615],
       [1.1026152 ],
       [1.52114151],
       [1.667

In [48]:
w_df = pd.DataFrame(w)
w_df

0
0    1.061645
1    1.117213
2    1.470808
3    1.130823
4    1.399325
..        ...
995  1.613499
996  1.731239
997  1.551804
998  1.986199
999  1.731286

[1000 rows x 1 columns]

In [49]:
w_df.values[:] = s.fit_transform(w_df)
w_df

0
0    1.548856
1    2.049468
2    5.234976
3    2.172081
4    4.590993
..        ...
995  6.520467
996  7.581178
997  5.964657
998  9.878091
999  7.581596

[1000 rows x 1 columns]

In [53]:
pd.DataFrame(s.fit_transform(w_df))

0
0    1.548856
1    2.049468
2    5.234976
3    2.172081
4    4.590993
..        ...
995  6.520467
996  7.581178
997  5.964657
998  9.878091
999  7.581596

[1000 rows x 1 columns]

In [37]:
s.fit(w)

MinMaxScaler(feature_range=(1, 10))

In [38]:
s.transform(w)

array([[ 1.54885612],
       [ 2.04946772],
       [ 5.23497601],
       [ 2.17208058],
       [ 4.59099306],
       [ 8.78699354],
       [ 9.07945367],
       [ 6.99516783],
       [ 3.79556277],
       [ 1.24348702],
       [ 6.19028299],
       [ 5.45594778],
       [ 9.63786546],
       [ 5.11082113],
       [ 2.23368778],
       [ 9.72106672],
       [ 4.89486572],
       [ 2.81600296],
       [ 9.32007982],
       [ 8.40117666],
       [ 3.69498294],
       [ 2.83897751],
       [ 3.37070156],
       [ 1.88870259],
       [ 5.72217126],
       [ 6.66701076],
       [ 7.53348086],
       [ 4.51810759],
       [ 4.52027809],
       [ 2.68018906],
       [ 2.55111153],
       [ 7.46265908],
       [ 1.6542675 ],
       [ 3.15080838],
       [ 8.49458362],
       [ 2.15751545],
       [ 4.332916  ],
       [ 4.11328892],
       [ 9.64655269],
       [ 2.7221198 ],
       [ 6.38427423],
       [ 7.58179842],
       [ 8.33512828],
       [ 8.85015942],
       [ 1.53292174],
       [ 1

In [30]:
w

array([[1.51064676, 1.6336066 , 1.02450609, 1.62040605, 1.00226517,
        1.39507258, 1.16892741, 1.12425649, 1.55361598, 1.68325097,
        1.19529991, 1.31540537, 1.77956172, 1.12528086, 1.26546023,
        1.79081666, 1.14001165, 1.54003879, 1.20119714, 1.69335596,
        1.06924698, 1.32338312, 1.78172939, 1.92059898, 1.25543055,
        1.2111327 , 1.74953708, 1.71839349, 1.14135463, 1.27194331,
        1.56139046, 1.22919918, 1.658648  , 1.05395126, 1.27008427,
        1.36075627, 1.35464777, 1.22833133, 1.77727077, 1.61493399,
        1.50232038, 1.11759478, 1.79284017, 1.62004121, 1.5039451 ,
        1.10473017, 1.42089519, 1.08600523, 1.79303458, 1.79951488,
        1.62753428, 1.49294502, 1.38025748, 1.1285266 , 1.77007666,
        1.40071345, 1.32423315, 1.70073544, 1.77535596, 1.13569853,
        1.23130485, 1.92704703, 1.87019218, 1.54707574, 1.82300479,
        1.05476457, 1.22390075, 1.233107  , 1.7133472 , 1.91603294,
        1.12265722, 1.76213748, 1.56572956, 1.58

In [39]:
d = {}

In [41]:
if d is not None:
    print(d)

{}


In [43]:
if not e:
    print("error")

NameError: name 'e' is not defined